services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENCODE_API_KEY=${OPENCODE_API_KEY}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - PRIVATE_API_KEY=${PRIVATE_API_KEY}
      - PRIVATE_API_PROXY_URL=${PRIVATE_API_PROXY_URL}
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - STORE_MODEL_IN_DB=true
      - LITELLM_MODE=PRODUCTION
      - LITELLM_LOG=ERROR